### ISSUE TITLE
Bones edited to objects attached to something else reset when another object is placed.

### ISSUE THREAD

**Issue by mrwallace888** [CapsAdmin/pac3#1015]
Title says it all. Basically, I made a test thingy. I took Dr. Breen, then attached a Father Grigori to him (lol). Then I edited the arm bones of Grigori to make him look like he's waving, then took a random prop and attached it to his hand. In doing so, the edited bones reset and went back to default. Deleting the object puts his bones back where they were edited.

There's also been a few times where like... I don't know what causes this specifically but sometimes if I go to attach stuff to bones (I think this happens in the same way where it's when you attach an object with edited bones and is attached to another object), when you go to select the bone and those little square selection thingies come up, they are all positioned as if the bones weren't edit.

With that Grigori example, even though the bones show his arms are raised, the white square node thingies outline that he's still t-posing. Due to this, sometimes objects attached will be placed to where the bone's original position was.

I know this is complicated, just bear with me here lol.

**Comment by CapsAdmin** [comment]
I think I fixed this a few hours ago. Can you test the develop branch?

**Comment by mrwallace888** [comment]
It's been modified but the bug persists. I loaded up an old outfit I had, and originally, both the objects and bones were edited and worked fine. I had an old develop version from probably a month or two back. It wasn't until a week or so ago I got a new develop version, and came across these issues. So basically, now when I load up an outfit, the bones are edited, but the objects attached are offset to where the bones were if the bones weren't edited. (if I put a ball on an edited hand, the hand would be edited but the ball would be placed to where the hand would be if the hand bone wasn't offset/edited). If I deleted the attached objects, the bones reset and I couldn't re-edit them. It's weird like that.

Trying your new version, now what it does is when I load the outfit the bones are reset. If I delete the objects attached to the parent attached to the owner, the parent's bones go back to how they were edited.

**Comment by mrwallace888** [comment]
Anything?

**Comment by CapsAdmin** [comment]
This is on my mind but I'm not sure if I fully understand it. Can you just send me an example outfit and explain what it's supposed to look like?

**Comment by mrwallace888** [comment]
Well I use this for NSFW purposes, and one of my NSFW outfits was actually how I originally found the bug.

I'll see if I can recreate the bug with an SFW/example outfit or something and send it to you. Or I'll just record it, idk.

**Comment by CapsAdmin** [comment]
I would prefer something SFW but if you can't figure it out or don't have time I don't mind.

**Comment by mrwallace888** [comment]
> 😄

Yeah I know lol. To be fair it was pretty much a given right from the start.
