### ISSUE TITLE
Skin value on entities/models resets to 1 on wear 

### ISSUE THREAD

**Issue by RonintothePowerof3** [CapsAdmin/pac3#1168]

**Comment by thegrb93** [comment]
This was fixed sometime ago

**Comment by RonintothePowerof3** [comment]
No it wasn't. I still have the issue, even with the updated version.

**Comment by Yagira** [comment]
For whatever reason there are two skin settings (I think it was something proxy related), one of them only appears when the model has select-able skins and they override each other so just set both of them to the skin that you want.

**Comment by thegrb93** [comment]
Do you have an outfit I can debug with? I fixed it very easily last time. If there's another bug then I need an outfit because my own outfit with skin works fine.

**Comment by thegrb93** [comment]
@RonintothePowerof3

**Comment by RonintothePowerof3** [comment]
just forget about it. i don't use this darn thing much anyway and know 0 about code.

**Comment by thegrb93** [comment]
I just wanted an outfit that has the problem
