### ISSUE TITLE
Screen shaking after resize player model

### ISSUE THREAD

**Issue by Quebecsy** [CapsAdmin/pac3#243]
When i resize my player model to be smaller then i crouch, my screen just gone crazy just like there's some earthquake on my screen. Please help me

**Comment by aumkarpraja** [comment]
It has to do with entity sizing. If the entity is re-sized (which makes the camera move up or down) it seems to insist on resetting the camera angle which makes PAC fight back. I think that's what's happening here.

**Comment by LUModder** [comment]
I thought this was fixed already

**Comment by aumkarpraja** [comment]
Nope, it's still happening on the latest version within most versions of NutScript (not sure about CW)

**Comment by LUModder** [comment]
Blaming update since its been doing it to me again on certain servers
